controllers/GamesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Games;
use app\models\GameGenre;
use app\models\GameComments;
use app\models\gamesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * GamesController implements the CRUD actions for Games model.
 */
class GamesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Games models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->request->isAjax) 
        {
            $session = Yii::$app->session;
            $request = Yii::$app->request;
            $comments = $request->post('comments'); 
            $gameID = $request->post('game'); 
            $model= new GameComments;
            $model->gameID=$gameID;
            $model->comments=$comments;
            $model->userID=$session['idUser'];
            $model->createDate=date('Y-m-d:H:i:s');
            $model->save(false);
            echo json_encode("OK");
        }
        $searchModel = new gamesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);


    }

    /**
     * Displays a single Games model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $data = $this->findModel($id);
        $customer = GameGenre::findOne($data->genreID);
        $genre = $customer->name;
        return $this->render('view', [
            'model' => $this->findModel($id),
            'genre' => $genre,
            'comments' => GameComments::find()->where(['gameID' => $data->creatorId])->all(),
        ]);
    }

    /**
     * Creates a new Games model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        Yii::setAlias('@pathCover', realpath(dirname(__FILE__).'/../../basic/web/'));
        
        $model = new Games();

        if ($model->load(Yii::$app->request->post()) ) {
            $file = UploadedFile::getInstance($model, 'gameCover');
            
            
           
            $file->saveAs(Yii::getAlias('@pathCover').'/images/' . $file->name);
            $model->gameCover = $file->name;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    /**
     * Updates an existing Games model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        Yii::setAlias('@pathCover', realpath(dirname(__FILE__).'/../../basic/web/'));
        if ($model->load(Yii::$app->request->post())) {
            $file = UploadedFile::getInstance($model, 'gameCover');
            
            
           
            $file->saveAs(Yii::getAlias('@pathCover').'/images/' . $file->name);
            $model->gameCover = $file->name;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Games model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Games model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Games the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Games::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    
}

controllers/UsersController.php
<?php
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\Users;
use app\models\GameComments;



class UsersController extends \yii\web\Controller
{
    
    public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
    	$model = new Users;
    	if(isset($_POST['Users']))
		{
			$request = Yii::$app->request;
			$data = Users::find()->where(['email' => $_POST['Users']['email'],'password' => $_POST['Users']['password']])->one();
			if(isset($data))
			{
				$session = Yii::$app->session;			
				$session->set('idUser',$data->id);
				$session->set('nameUser',$data->name);
				
				Yii::$app->response->redirect(array('home'));
			}else{
				var_dump($data);
			}
			
			
		}
    	return $this->render('login', ['model' => $model,]);
    }

    public function actionLogout()
    {
    	$session = Yii::$app->session;
    	// close a session
		$session->close();
		$session = Yii::$app->session;
		$session->remove('idUser');
		$session->remove('nameUser');
		$session->destroy();
		
    	Yii::$app->response->redirect(array('users/login'));
    }

    public function actionGetfromajax()
    {
    	$session = Yii::$app->session;
    	$request = Yii::$app->request;
    	$comments = $request->post('comments'); 
    	$gameID = $request->post('gameID'); 
        $model= new GameComments;
        $model->gameID=$gameID;
        $model->comments=$comments;
        $model->userID=$session['idUser'];
        $model->createDate=date('Y-m-d:H:i:s');
        $model->save(false);
        echo json_encode("OK");
    }

    public function actionCreate()
    {

        
        
        $model = new Users();

        if ($model->load(Yii::$app->request->post()) && $model->save() ) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
$session = Yii::$app->session;
?>
<?php $this->beginPage() ?>
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />

    <!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::$app->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::$app->request->baseUrl; ?>/css/print.css" media="print" />
    <!--[if lt IE 8]>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::$app->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::$app->request->baseUrl; ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::$app->request->baseUrl; ?>/css/form.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <title><?= Html::encode($this->title) ?></title>
</head>

<body>

<div class="container" id="page">

    <div id="header">
        <div id="logo"><?php echo Html::encode(Yii::$app->name); ?></div>
    </div><!-- header -->

    <div id="mainmenu">
       <?php

       if(isset($session['nameUser']) || $session['nameUser']!= '')
       {
            echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => 
                [
                    ['label' => 'Home', 'url' => ['/home']],
                    ['label' => 'Games', 'url' => ['/games']],
                    ['label' => 'Create Games Page', 'url' => ['/games/create']],
                    ['label' => 'Logout('.$session['nameUser'].')', 'url' => ['/users/logout']],
                ],
            ]);
       }else{
            echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => 
                [
                    ['label' => 'Home', 'url' => ['/home']],
                    ['label' => 'Games', 'url' => ['/games']],
                    // ['label' => 'Create Games Page', 'url' => ['/games/create']],
                    ['label' => 'Login', 'url' => ['/users/login']],
                ],
            ]);
       }
        
        
?>
        
    </div><!-- mainmenu -->

    
        <?= $content ?>
    
    <div class="clear"></div>

    <div id="footer">
        Copyright &copy; <?php echo date('Y'); ?> by Francesco.<br/>
        All Rights Reserved.<br/>
        <?php echo Yii::powered(); ?>
    </div><!-- footer -->

</div><!-- page -->
<script type="text/javascript">
    $('#signupTombol').on('click', function(event){
    {
        window.open("create","_self")
    }
})
</script>
</body>
</html>