models/Games.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "game".
 *
 * @property integer $id
 * @property string $name
 * @property string $createDate
 * @property integer $creatorId
 * @property string $gameCover
 * @property string $descr
 * @property string $developer
 * @property string $publisher
 * @property integer $genreID
 *
 * @property Users $creator
 * @property GameGenre $genre
 * @property GameComments[] $gameComments
 */
class Games extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'game';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'createDate', 'creatorId', 'gameCover', 'descr', 'developer', 'publisher', 'genreID'], 'required'],
            [['createDate'], 'safe'],
            [['creatorId', 'genreID'], 'integer'],
            [['descr'], 'string'],
            [['name', 'developer', 'publisher'], 'string', 'max' => 50],
            [['gameCover'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'createDate' => 'Create Date',
            'creatorId' => 'Creator ID',
            'gameCover' => 'Game Cover',
            'descr' => 'Descr',
            'developer' => 'Developer',
            'publisher' => 'Publisher',
            'genreID' => 'Genre ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreator()
    {
        return $this->hasOne(Users::className(), ['id' => 'creatorId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGenre()
    {
        return $this->hasOne(GameGenre::className(), ['id' => 'genreID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGameComments()
    {
        return $this->hasMany(GameComments::className(), ['gameID' => 'id']);
    }

    /**
     * @inheritdoc
     * @return GameQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new GameQuery(get_called_class());
    }
}

controllers/GamesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Games;
use app\models\GameGenre;
use app\models\GameComments;
use app\models\gamesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * GamesController implements the CRUD actions for Games model.
 */
class GamesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Games models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->request->isAjax) 
        {
            $session = Yii::$app->session;
            $request = Yii::$app->request;
            $comments = $request->post('comments'); 
            $gameID = $request->post('game'); 
            $model= new GameComments;
            $model->gameID=$gameID;
            $model->comments=$comments;
            $model->userID=$session['idUser'];
            $model->createDate=date('Y-m-d:H:i:s');
            $model->save(false);
            echo json_encode("OK");
        }
        $searchModel = new gamesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);


    }

    /**
     * Displays a single Games model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $data = $this->findModel($id);
        $customer = GameGenre::findOne($data->genreID);
        $genre = $customer->name;
        return $this->render('view', [
            'model' => $this->findModel($id),
            'genre' => $genre,
            'comments' => GameComments::find()->where(['gameID' => $data->creatorId])->all(),
        ]);
    }

    /**
     * Creates a new Games model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        Yii::setAlias('@pathCover', realpath(dirname(__FILE__).'/../../basic/web/'));
        
        $model = new Games();

        if ($model->load(Yii::$app->request->post()) ) {
            $file = UploadedFile::getInstance($model, 'gameCover');
            
            
           
            $file->saveAs(Yii::getAlias('@pathCover').'/images/' . $file->name);
            $model->gameCover = $file->name;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    /**
     * Updates an existing Games model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        Yii::setAlias('@pathCover', realpath(dirname(__FILE__).'/../../basic/web/'));
        if ($model->load(Yii::$app->request->post())) {
            $file = UploadedFile::getInstance($model, 'gameCover');
            
            
           
            $file->saveAs(Yii::getAlias('@pathCover').'/images/' . $file->name);
            $model->gameCover = $file->name;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Games model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Games model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Games the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Games::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    
}

views/games/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Games */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="games-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'createDate')->textInput() ?>

    <?= $form->field($model, 'creatorId')->textInput() ?>

    <?= $form->field($model, 'gameCover')->fileInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descr')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'developer')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'publisher')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'genreID')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/games/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\gamesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="games-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

     <?= // $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= //$form->field($model, 'createDate') ?>

    <?= //$form->field($model, 'creatorId') ?>

    <?= $form->field($model, 'gameCover') ?>

    <?php // echo $form->field($model, 'descr') ?>

    <?php // echo $form->field($model, 'developer') ?>

    <?php // echo $form->field($model, 'publisher') ?>

    <?php // echo $form->field($model, 'genreID') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/games/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Create Games';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/games/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\gamesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Games', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            // 'id',
            'name',
            // 'createDate',
            // 'creatorId',
            'gameCover'=>array('format' => 'html','value' => function($data) 
                { 
                    return Html::a(Html::img('http://localhost'.Yii::$app->homeUrl.'images/'.$data['gameCover'],['width'=>'50']), ['games/view', 'id' => $data['id']], ['class' => 'profile-link']) ;
                }),
            // 'descr:ntext',
            // 'developer',
            // 'publisher',
            // 'genreID',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/games/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Update Games: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="games-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/games/view.php
<?php
$session = Yii::$app->session;          
                
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if($model->creatorId == $session['idUser'])            
                { echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']); }
        ?>
        <?php /* Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) */ ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'createDate',
            [
                'attribute'=>'Genre',
                'value'=>$genre,
            ],
            [
                'attribute'=>'photo',
                'value'=>'http://localhost'.Yii::$app->homeUrl.'images/'.$model->gameCover,
                'format' => ['image',['width'=>'100','height'=>'100']],
            ],
            'descr:ntext',
            'developer',
            'creatorId',
            'publisher',
            
        ],
    ]) ?>
<?php 
if($session['idUser'])
{
?>   
<textarea id='Isicomment' rows='4' cols='60' ></textarea>
<br /><br />
<button id='comment'>Comment Now</button>    
<br /><br />
<?php } ?>
<h1>Comments</h1>
<div>
<?php 
foreach ($comments as $key) {
?>
<div class="view">
    <p><?php echo $key->comments; ?></p>
</div>
<?php    
}
?>
</div>
<script type="text/javascript">
$(function() {
    var gameID = '<?php echo $model->id; ?>';
    var userID = '<?php echo Yii::$app->session['idUser']; ?>';
    var url = '<?php echo "http://".$_SERVER["SERVER_NAME"]. Yii::$app->homeUrl."games"; ?>';
    var comment = "";
    $("#comment").click( function()
    {
        
        comment = $("#Isicomment").val();
        var formData = {comments:comment,game:gameID,user:userID,_csrf : '<?=Yii::$app->request->getCsrfToken()?>'};
        $.ajax({
                    url : url,
                    type: "POST",
                    data : formData,
                    success: function(data, textStatus, jqXHR)
                    {
                        location.reload(true);
                    },
                    error: function (jqXHR, textStatus, errorThrown)
                    {
                 
                    }
                });
    });
});
</script>